import { useCallback } from "react";
import { ArrowLeft, Download, Plus, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import type { Invoice, InvoiceItem } from "@shared/schema";

interface InvoicePreviewProps {
  invoice: Invoice & { items: InvoiceItem[] };
  onBack: () => void;
  onNewScan: () => void;
}

export function InvoicePreview({ invoice, onBack, onNewScan }: InvoicePreviewProps) {
  const total = invoice.items.reduce((sum, item) => sum + item.quantity * item.rate, 0);

  const generatePDF = useCallback(async () => {
    const { jsPDF } = await import("jspdf");
    const autoTable = (await import("jspdf-autotable")).default;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    doc.setFillColor(20, 30, 48);
    doc.rect(0, 0, pageWidth, 50, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("INVOICE", 20, 25);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(invoice.invoiceNumber, 20, 35);

    doc.setFontSize(10);
    doc.text(`Date: ${new Date(invoice.createdAt).toLocaleDateString("en-GB")}`, pageWidth - 20, 25, { align: "right" });
    doc.text(`Currency: ${invoice.currency}`, pageWidth - 20, 35, { align: "right" });

    doc.setTextColor(50, 50, 50);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Bill To:", 20, 62);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(invoice.clientName, 20, 70);
    doc.text(invoice.clientAddress, 20, 77);

    doc.setFont("helvetica", "bold");
    doc.text("From:", pageWidth - 80, 62);
    doc.setFont("helvetica", "normal");
    doc.text("Digitizer", pageWidth - 80, 70);
    doc.text("Islamabad, Pakistan", pageWidth - 80, 77);

    const tableData = invoice.items.map((item, i) => [
      (i + 1).toString(),
      item.description,
      item.quantity.toString(),
      item.rate.toFixed(2),
      (item.quantity * item.rate).toFixed(2),
    ]);

    autoTable(doc, {
      startY: 90,
      head: [["#", "Description", "Qty", "Rate (AED)", "Amount (AED)"]],
      body: tableData,
      theme: "grid",
      headStyles: {
        fillColor: [20, 30, 48],
        textColor: [255, 255, 255],
        fontSize: 9,
        fontStyle: "bold",
      },
      bodyStyles: {
        fontSize: 9,
        textColor: [50, 50, 50],
      },
      alternateRowStyles: {
        fillColor: [245, 247, 250],
      },
      columnStyles: {
        0: { cellWidth: 12, halign: "center" },
        1: { cellWidth: "auto" },
        2: { cellWidth: 20, halign: "right" },
        3: { cellWidth: 30, halign: "right" },
        4: { cellWidth: 35, halign: "right" },
      },
      margin: { left: 20, right: 20 },
    });

    const finalY = (doc as any).lastAutoTable?.finalY || 150;

    doc.setFillColor(245, 247, 250);
    doc.rect(pageWidth - 90, finalY + 10, 70, 25, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    doc.text("Total AED", pageWidth - 85, finalY + 22);
    doc.setFontSize(14);
    doc.setTextColor(20, 30, 48);
    doc.text(total.toFixed(2), pageWidth - 25, finalY + 30, { align: "right" });

    doc.setDrawColor(200, 200, 200);
    doc.line(20, finalY + 50, pageWidth - 20, finalY + 50);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by Digitizer - Bazaar Note to Invoice", pageWidth / 2, finalY + 58, { align: "center" });

    doc.save(`${invoice.invoiceNumber}.pdf`);
  }, [invoice, total]);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={onBack} data-testid="button-back-to-editor">
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div>
            <h2 className="text-xl font-semibold" data-testid="text-preview-title">Invoice Preview</h2>
            <p className="text-sm text-muted-foreground">
              <span className="font-mono font-medium">{invoice.invoiceNumber}</span>
              {" "} &middot; {invoice.clientName}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="secondary" onClick={onNewScan} data-testid="button-new-scan-preview">
            <Plus className="w-4 h-4 mr-2" />
            New Scan
          </Button>
          <Button onClick={generatePDF} data-testid="button-generate-pdf">
            <Download className="w-4 h-4 mr-2" />
            Generate PDF
          </Button>
        </div>
      </div>

      <Card className="p-6 max-w-3xl mx-auto">
        <div className="space-y-6">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <FileText className="w-5 h-5 text-primary" />
                <h3 className="text-lg font-bold">INVOICE</h3>
              </div>
              <p className="font-mono text-sm text-muted-foreground">{invoice.invoiceNumber}</p>
            </div>
            <div className="text-right">
              <Badge variant="secondary" data-testid="badge-status">{invoice.status}</Badge>
              <p className="text-xs text-muted-foreground mt-1">
                {new Date(invoice.createdAt).toLocaleDateString("en-GB", {
                  day: "2-digit",
                  month: "short",
                  year: "numeric",
                })}
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-6">
            <div>
              <p className="text-xs text-muted-foreground mb-1 uppercase tracking-wider">Bill To</p>
              <p className="font-medium text-sm">{invoice.clientName}</p>
              <p className="text-sm text-muted-foreground">{invoice.clientAddress}</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-muted-foreground mb-1 uppercase tracking-wider">From</p>
              <p className="font-medium text-sm">Digitizer</p>
              <p className="text-sm text-muted-foreground">Islamabad, Pakistan</p>
            </div>
          </div>

          <div className="border rounded-md">
            <table className="w-full" data-testid="table-preview-items">
              <thead>
                <tr className="bg-muted/30 border-b">
                  <th className="text-left text-xs font-medium text-muted-foreground px-4 py-2.5 w-8">#</th>
                  <th className="text-left text-xs font-medium text-muted-foreground px-4 py-2.5">Description</th>
                  <th className="text-right text-xs font-medium text-muted-foreground px-4 py-2.5 w-16">Qty</th>
                  <th className="text-right text-xs font-medium text-muted-foreground px-4 py-2.5 w-24">Rate</th>
                  <th className="text-right text-xs font-medium text-muted-foreground px-4 py-2.5 w-28">Amount</th>
                </tr>
              </thead>
              <tbody>
                {invoice.items.map((item, i) => (
                  <tr key={item.id} className="border-b last:border-b-0" data-testid={`row-preview-${i}`}>
                    <td className="px-4 py-2.5 text-sm text-muted-foreground">{i + 1}</td>
                    <td className="px-4 py-2.5 text-sm font-mono font-medium">{item.description}</td>
                    <td className="px-4 py-2.5 text-sm text-right">{item.quantity}</td>
                    <td className="px-4 py-2.5 text-sm text-right font-mono">{item.rate.toFixed(2)}</td>
                    <td className="px-4 py-2.5 text-sm text-right font-mono font-medium">
                      {(item.quantity * item.rate).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="flex justify-end">
            <div className="bg-muted/30 rounded-md px-5 py-3 min-w-[180px]">
              <div className="flex items-center justify-between gap-4">
                <span className="text-sm text-muted-foreground">Total {invoice.currency}</span>
                <span className="text-xl font-bold font-mono" data-testid="text-preview-total">
                  {total.toFixed(2)}
                </span>
              </div>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
}
